version: '3'
services:
  widget-recent:
    build:
      context: ./widget-recent
      dockerfile: Dockerfile
    ports:
      - "8081:3000" # Maps external port 8081 to internal port 3000
    networks:
      - vue-network

  settings:
    build:
      context: ./settings
      dockerfile: Dockerfile
    ports:
      - "8082:3000" # Maps external port 8082 to internal port 3000
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge